In [7]:
import torch

logits = torch.randn(1,2)

In [8]:
logits

tensor([[-0.2820, -0.6923]])

In [9]:


act1 = torch.nn.Sigmoid()
act2 = torch.nn.Softmax()

print(act1(logits))
print(act2(logits))

tensor([[0.4300, 0.3335]])
tensor([[0.6012, 0.3988]])


/root/anaconda3/envs/cibmtr/lib/python3.10/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
